CXX = g++
CXXFLAGS= -Wformat -O3

all: from_unionbed_to_ratio_per_window_CC0 from_unionbed_to_ratio_per_window_CC0_v2

from_unionbed_to_ratio_per_window_CC0: 
	$(CXX) -o $@ $(CXXFLAGS) from_unionbed_to_ratio_per_window_CC0.cpp

from_unionbed_to_ratio_per_window_CC0_v2: 
	$(CXX) -o $@ $(CXXFLAGS) from_unionbed_to_ratio_per_window_CC0_v2.cpp
	
clean:
