args<-commandArgs(TRUE)
#args[1]
output_file = paste(args[1], ".DNAcopyout", sep = "")
#output_file
wjpg = paste(args[1], ".w.jpg", sep = "")
pjpg = paste(args[1], ".p.jpg", sep = "")
pdf_name = paste(args[1], ".pdf", sep = "")
pdf(file=pdf_name)
library(DNAcopy)
x <-read.table(args[1], header=T)
x.object <-CNA(genomdat=x[,3], chrom=x[,1],maploc=x[,2], data.type='logratio')
smoothed.x.object <- smooth.CNA(x.object)
segment.smoothed.x.object <- segment(smoothed.x.object, verbose=1)
x2=segment.smoothed.x.object$output
write.table(x2[,2:6], file=output_file, row.names=F, col.names=F, quote=F, sep="\t")
plot(segment.smoothed.x.object, plot.type="w")
dev.copy(jpeg,wjpg)
dev.off()
plot(segment.smoothed.x.object, plot.type="p")
dev.copy(jpeg,pjpg)
dev.off() 
